set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
"Plugin 'flazz/vim-colorschemes'
Plugin 'jiangmiao/auto-pairs'
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'romainl/Apprentice'
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/syntastic'

call vundle#end()
filetype plugin indent on    " required

"my settings
syntax on
colorscheme apprentice
set encoding=utf-8

set nocompatible
set backspace=2
set ruler
set number

"for tmux background
set t_ut=

set tabstop=4
set shiftwidth=4
set expandtab
set smarttab

"NERDTree plugin options
let g:NERDTreeDirArrows = 1
let g:NERDTreeDirArrowExpandable = '>'
let g:NERDTreeDirArrowCollapsible = '<'

"Mappings
noremap <F2> :set number!<CR>
noremap <F3> :set relativenumber!<CR>
noremap <F4> :NERDTreeToggle<CR>
noremap [[ m'A;<Esc>``

noremap ; l
noremap l k
norema k j
noremap j h

"for gtk
let g:syntastic_c_config_file = '.syntastic_c_config'
