set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
"Plugin 'flazz/vim-colorschemes'
Plugin 'jiangmiao/auto-pairs'
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'romainl/Apprentice'
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/syntastic'
Plugin 'Valloric/YouCompleteMe'
Plugin 'irrationalistic/vim-tasks'
Plugin 'vim-airline/vim-airline' " fancy statusline
Plugin 'vim-airline/vim-airline-themes' " themes for vim-airline
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'powerline/powerline'
Plugin 'garbas/vim-snipmate'
" Optional:
Plugin 'honza/vim-snippets'

"Plugin 'vim-ctrlspace/vim-ctrlspace'

call vundle#end()
filetype plugin indent on    " required

"my settings
syntax on
colorscheme apprentice
set encoding=utf-8
set nocompatible
set backspace=2
set ruler
set number
set laststatus=2
set showtabline=0
set hidden
set pastetoggle=<leader>v

"for tmux background
set t_ut=

set tabstop=4
set shiftwidth=4
set expandtab
set smarttab

"NERDTree plugin options
let g:NERDTreeDirArrows = 1
let g:NERDTreeDirArrowExpandable = '>'
let g:NERDTreeDirArrowCollapsible = '<'
let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'
"let g:airline#extensions#tabline#enabled = 1

"Mappings
noremap <F2> :set number!<CR>
noremap <F3> :set relativenumber!<CR>
noremap <F4> :NERDTreeToggle<CR>
noremap [[ m'A;<Esc>``
nmap <leader>A :<C-r><C-w><Left>

noremap ; l
noremap l k
norema k j
noremap j h

"for gtk
